name: Metrics
on:
  schedule: [{cron: "* 10 * * *"}]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          user: Riteri
          template: classic
          base: header
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_details: percentage
          config_timezone: Europe/Warsaw
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_lines: yes
          plugin_traffic: no
          
